services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: alibaba
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sre_bootcamp
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alibaba -d sre_bootcamp"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LOCAL_DATABASE_URL: postgresql://alibaba:password@db:5432/sre_bootcamp
      NODE_ENV: development
      PORT: 3004
    ports:
      - "3004:3004"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
