name: Pull Request Checks

on:
  pull_request:
    paths:
      - "src/**"
      - "Dockerfile"
      - "package*.json"
      - "tsconfig.json"

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: alibaba0010/sre-bootcamp
      DOCKER_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: |
          npm install eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin --save-dev
          npx eslint . --ext .ts

      - name: Run tests
        run: npm test

      - name: Build API
        run: npm run build

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.DOCKER_IMAGE }}:pr-${{ github.event.pull_request.number }}
